obstacle_range: 2.0
raytrace_range: 3.0
inflation_radius: 0.25

footprint: [[0.26, 0.19], 
            [0.26, 0.014],
            [0.31, 0.014],
            [0.31, -0.014],
            [0.26, -0.014],
            [0.26, -0.19],
            [-0.27, -0.19],
            [-0.27, 0.19]]

controller_frequency: 10.0
controller_patience: 15.0
# clearing_radius: 0.25
footprint_padding: 0.02
transform_tolerance: 0.2
map_type: costmap

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true, expected_update_rate: 0.2}